* What's This?

This is an Emacs Lisp package that implements the same functionality as Gilles Castel's [[https://github.com/gillescastel/inkscape-figures][Inkscape figure manager]]. It is designed to be more convenient for Emacs users, making use of the [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Minibuffer.html][minibuffer]] for selecting figures, rather than an external menu such as [[https://github.com/davatorium/rofi][rofi]], [[https://github.com/chipsenkbeil/choose][choose]], or [[https://tools.suckless.org/dmenu/][dmenu]].

* Installation

** Using package.el
Download ~figedit.el~ to a place on your filesystem, then add the following to your init file:

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/figedit.el")
(require 'figedit)
#+end_src

Or with ~use-package~:

#+begin_src emacs-lisp
(use-package figedit :load-path "/path/to/figedit.el")
#+end_src

** Using [[https://github.com/radian-software/straight.el][straight.el]]
#+begin_src emacs-lisp
(use-package figedit
  :straight (figedit :type git
                     :host github
                     :repo "olnw/figedit"))
#+end_src

** Using [[https://github.com/progfolio/elpaca][Elpaca]]
#+begin_src emacs-lisp
(use-package figedit
  :elpaca (figedit :host github
                   :repo "olnw/figedit"))
#+end_src

* Customisation

Figedit can be customised by running ~M-x customize-group RET figedit RET~.

* Usage

Figedit provides two interactive functions: these are ~figedit-insert~ and ~figedit-edit~.

The behaviour of ~figedit-insert~ is to insert the LaTeX code needed to render a figure into the current buffer. When called, the user is prompted to select a figure file. If the figure already exists on the user's filesystem, this is all that is done. If the figure does not exist, it is created from a template file. The newly created figure is then opened with ~figedit-edit-program~, which defaults to [[https://inkscape.org][Inkscape]], a free vector graphics editor.

The function ~figedit-edit~ is used for editing existing figures. When called, the user is prompted to select a figure file. This figure is then opened with ~figedit-edit-program~.

* License

This package is licensed under the GPL v3. See the ~COPYING~ file for the full license text.
